version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Europe/Helsinki
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Europe/Helsinki
    groups:
      github-actions:
        patterns:
          - "*"
