project = 'gmshparser'
copyright = '2020, Jukka Aho'
author = 'Jukka Aho'
release = '0.1.0'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'recommonmark']
master_doc = 'index'
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
add_module_names = False
